// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_Payment.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Msg_5fPayment_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Msg_5fPayment_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012002 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Msg_5fPayment_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Msg_5fPayment_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Msg_5fPayment_2eproto;
class CreatePaymentAck;
class CreatePaymentAckDefaultTypeInternal;
extern CreatePaymentAckDefaultTypeInternal _CreatePaymentAck_default_instance_;
class CreatePaymentReq;
class CreatePaymentReqDefaultTypeInternal;
extern CreatePaymentReqDefaultTypeInternal _CreatePaymentReq_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::CreatePaymentAck* Arena::CreateMaybeMessage<::CreatePaymentAck>(Arena*);
template<> ::CreatePaymentReq* Arena::CreateMaybeMessage<::CreatePaymentReq>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class CreatePaymentReq PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CreatePaymentReq) */ {
 public:
  inline CreatePaymentReq() : CreatePaymentReq(nullptr) {};
  virtual ~CreatePaymentReq();

  CreatePaymentReq(const CreatePaymentReq& from);
  CreatePaymentReq(CreatePaymentReq&& from) noexcept
    : CreatePaymentReq() {
    *this = ::std::move(from);
  }

  inline CreatePaymentReq& operator=(const CreatePaymentReq& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreatePaymentReq& operator=(CreatePaymentReq&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CreatePaymentReq& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreatePaymentReq* internal_default_instance() {
    return reinterpret_cast<const CreatePaymentReq*>(
               &_CreatePaymentReq_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(CreatePaymentReq& a, CreatePaymentReq& b) {
    a.Swap(&b);
  }
  inline void Swap(CreatePaymentReq* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreatePaymentReq* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CreatePaymentReq* New() const final {
    return CreateMaybeMessage<CreatePaymentReq>(nullptr);
  }

  CreatePaymentReq* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CreatePaymentReq>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CreatePaymentReq& from);
  void MergeFrom(const CreatePaymentReq& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreatePaymentReq* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CreatePaymentReq";
  }
  protected:
  explicit CreatePaymentReq(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Msg_5fPayment_2eproto);
    return ::descriptor_table_Msg_5fPayment_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderIDFieldNumber = 1,
    kPlatformFieldNumber = 2,
    kChannelFieldNumber = 3,
    kRoleIDFieldNumber = 4,
    kAccountIDFieldNumber = 6,
    kServerIDFieldNumber = 5,
    kProductIDFieldNumber = 7,
    kBuyIDFieldNumber = 8,
    kProxyIDFieldNumber = 9,
    kClientIDFieldNumber = 10,
  };
  // string OrderID = 1;
  void clear_orderid();
  const std::string& orderid() const;
  void set_orderid(const std::string& value);
  void set_orderid(std::string&& value);
  void set_orderid(const char* value);
  void set_orderid(const char* value, size_t size);
  std::string* mutable_orderid();
  std::string* release_orderid();
  void set_allocated_orderid(std::string* orderid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_orderid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_orderid(
      std::string* orderid);
  private:
  const std::string& _internal_orderid() const;
  void _internal_set_orderid(const std::string& value);
  std::string* _internal_mutable_orderid();
  public:

  // int32 Platform = 2;
  void clear_platform();
  ::PROTOBUF_NAMESPACE_ID::int32 platform() const;
  void set_platform(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_platform() const;
  void _internal_set_platform(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 Channel = 3;
  void clear_channel();
  ::PROTOBUF_NAMESPACE_ID::int32 channel() const;
  void set_channel(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_channel() const;
  void _internal_set_channel(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // uint64 RoleID = 4;
  void clear_roleid();
  ::PROTOBUF_NAMESPACE_ID::uint64 roleid() const;
  void set_roleid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_roleid() const;
  void _internal_set_roleid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 AccountID = 6;
  void clear_accountid();
  ::PROTOBUF_NAMESPACE_ID::uint64 accountid() const;
  void set_accountid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_accountid() const;
  void _internal_set_accountid(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // int32 ServerID = 5;
  void clear_serverid();
  ::PROTOBUF_NAMESPACE_ID::int32 serverid() const;
  void set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_serverid() const;
  void _internal_set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 ProductID = 7;
  void clear_productid();
  ::PROTOBUF_NAMESPACE_ID::int32 productid() const;
  void set_productid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_productid() const;
  void _internal_set_productid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 BuyID = 8;
  void clear_buyid();
  ::PROTOBUF_NAMESPACE_ID::int32 buyid() const;
  void set_buyid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_buyid() const;
  void _internal_set_buyid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 ProxyID = 9;
  void clear_proxyid();
  ::PROTOBUF_NAMESPACE_ID::int32 proxyid() const;
  void set_proxyid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_proxyid() const;
  void _internal_set_proxyid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 ClientID = 10;
  void clear_clientid();
  ::PROTOBUF_NAMESPACE_ID::int32 clientid() const;
  void set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_clientid() const;
  void _internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:CreatePaymentReq)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr orderid_;
  ::PROTOBUF_NAMESPACE_ID::int32 platform_;
  ::PROTOBUF_NAMESPACE_ID::int32 channel_;
  ::PROTOBUF_NAMESPACE_ID::uint64 roleid_;
  ::PROTOBUF_NAMESPACE_ID::uint64 accountid_;
  ::PROTOBUF_NAMESPACE_ID::int32 serverid_;
  ::PROTOBUF_NAMESPACE_ID::int32 productid_;
  ::PROTOBUF_NAMESPACE_ID::int32 buyid_;
  ::PROTOBUF_NAMESPACE_ID::int32 proxyid_;
  ::PROTOBUF_NAMESPACE_ID::int32 clientid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Msg_5fPayment_2eproto;
};
// -------------------------------------------------------------------

class CreatePaymentAck PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:CreatePaymentAck) */ {
 public:
  inline CreatePaymentAck() : CreatePaymentAck(nullptr) {};
  virtual ~CreatePaymentAck();

  CreatePaymentAck(const CreatePaymentAck& from);
  CreatePaymentAck(CreatePaymentAck&& from) noexcept
    : CreatePaymentAck() {
    *this = ::std::move(from);
  }

  inline CreatePaymentAck& operator=(const CreatePaymentAck& from) {
    CopyFrom(from);
    return *this;
  }
  inline CreatePaymentAck& operator=(CreatePaymentAck&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const CreatePaymentAck& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CreatePaymentAck* internal_default_instance() {
    return reinterpret_cast<const CreatePaymentAck*>(
               &_CreatePaymentAck_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(CreatePaymentAck& a, CreatePaymentAck& b) {
    a.Swap(&b);
  }
  inline void Swap(CreatePaymentAck* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CreatePaymentAck* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline CreatePaymentAck* New() const final {
    return CreateMaybeMessage<CreatePaymentAck>(nullptr);
  }

  CreatePaymentAck* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<CreatePaymentAck>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const CreatePaymentAck& from);
  void MergeFrom(const CreatePaymentAck& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CreatePaymentAck* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "CreatePaymentAck";
  }
  protected:
  explicit CreatePaymentAck(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_Msg_5fPayment_2eproto);
    return ::descriptor_table_Msg_5fPayment_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOrderIDFieldNumber = 2,
    kRetCodeFieldNumber = 1,
  };
  // string OrderID = 2;
  void clear_orderid();
  const std::string& orderid() const;
  void set_orderid(const std::string& value);
  void set_orderid(std::string&& value);
  void set_orderid(const char* value);
  void set_orderid(const char* value, size_t size);
  std::string* mutable_orderid();
  std::string* release_orderid();
  void set_allocated_orderid(std::string* orderid);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_orderid();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_orderid(
      std::string* orderid);
  private:
  const std::string& _internal_orderid() const;
  void _internal_set_orderid(const std::string& value);
  std::string* _internal_mutable_orderid();
  public:

  // uint32 RetCode = 1;
  void clear_retcode();
  ::PROTOBUF_NAMESPACE_ID::uint32 retcode() const;
  void set_retcode(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_retcode() const;
  void _internal_set_retcode(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:CreatePaymentAck)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr orderid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 retcode_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Msg_5fPayment_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// CreatePaymentReq

// string OrderID = 1;
inline void CreatePaymentReq::clear_orderid() {
  orderid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CreatePaymentReq::orderid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.OrderID)
  return _internal_orderid();
}
inline void CreatePaymentReq::set_orderid(const std::string& value) {
  _internal_set_orderid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.OrderID)
}
inline std::string* CreatePaymentReq::mutable_orderid() {
  // @@protoc_insertion_point(field_mutable:CreatePaymentReq.OrderID)
  return _internal_mutable_orderid();
}
inline const std::string& CreatePaymentReq::_internal_orderid() const {
  return orderid_.Get();
}
inline void CreatePaymentReq::_internal_set_orderid(const std::string& value) {
  
  orderid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CreatePaymentReq::set_orderid(std::string&& value) {
  
  orderid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CreatePaymentReq.OrderID)
}
inline void CreatePaymentReq::set_orderid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  orderid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:CreatePaymentReq.OrderID)
}
inline void CreatePaymentReq::set_orderid(const char* value,
    size_t size) {
  
  orderid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CreatePaymentReq.OrderID)
}
inline std::string* CreatePaymentReq::_internal_mutable_orderid() {
  
  return orderid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CreatePaymentReq::release_orderid() {
  // @@protoc_insertion_point(field_release:CreatePaymentReq.OrderID)
  return orderid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CreatePaymentReq::set_allocated_orderid(std::string* orderid) {
  if (orderid != nullptr) {
    
  } else {
    
  }
  orderid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), orderid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CreatePaymentReq.OrderID)
}
inline std::string* CreatePaymentReq::unsafe_arena_release_orderid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:CreatePaymentReq.OrderID)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return orderid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CreatePaymentReq::unsafe_arena_set_allocated_orderid(
    std::string* orderid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (orderid != nullptr) {
    
  } else {
    
  }
  orderid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      orderid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CreatePaymentReq.OrderID)
}

// int32 Platform = 2;
inline void CreatePaymentReq::clear_platform() {
  platform_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::_internal_platform() const {
  return platform_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::platform() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.Platform)
  return _internal_platform();
}
inline void CreatePaymentReq::_internal_set_platform(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  platform_ = value;
}
inline void CreatePaymentReq::set_platform(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_platform(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.Platform)
}

// int32 Channel = 3;
inline void CreatePaymentReq::clear_channel() {
  channel_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::_internal_channel() const {
  return channel_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::channel() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.Channel)
  return _internal_channel();
}
inline void CreatePaymentReq::_internal_set_channel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  channel_ = value;
}
inline void CreatePaymentReq::set_channel(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_channel(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.Channel)
}

// uint64 RoleID = 4;
inline void CreatePaymentReq::clear_roleid() {
  roleid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CreatePaymentReq::_internal_roleid() const {
  return roleid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CreatePaymentReq::roleid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.RoleID)
  return _internal_roleid();
}
inline void CreatePaymentReq::_internal_set_roleid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  roleid_ = value;
}
inline void CreatePaymentReq::set_roleid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_roleid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.RoleID)
}

// int32 ServerID = 5;
inline void CreatePaymentReq::clear_serverid() {
  serverid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::_internal_serverid() const {
  return serverid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::serverid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.ServerID)
  return _internal_serverid();
}
inline void CreatePaymentReq::_internal_set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  serverid_ = value;
}
inline void CreatePaymentReq::set_serverid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_serverid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.ServerID)
}

// uint64 AccountID = 6;
inline void CreatePaymentReq::clear_accountid() {
  accountid_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CreatePaymentReq::_internal_accountid() const {
  return accountid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 CreatePaymentReq::accountid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.AccountID)
  return _internal_accountid();
}
inline void CreatePaymentReq::_internal_set_accountid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  accountid_ = value;
}
inline void CreatePaymentReq::set_accountid(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_accountid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.AccountID)
}

// int32 ProductID = 7;
inline void CreatePaymentReq::clear_productid() {
  productid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::_internal_productid() const {
  return productid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::productid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.ProductID)
  return _internal_productid();
}
inline void CreatePaymentReq::_internal_set_productid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  productid_ = value;
}
inline void CreatePaymentReq::set_productid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_productid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.ProductID)
}

// int32 BuyID = 8;
inline void CreatePaymentReq::clear_buyid() {
  buyid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::_internal_buyid() const {
  return buyid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::buyid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.BuyID)
  return _internal_buyid();
}
inline void CreatePaymentReq::_internal_set_buyid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  buyid_ = value;
}
inline void CreatePaymentReq::set_buyid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_buyid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.BuyID)
}

// int32 ProxyID = 9;
inline void CreatePaymentReq::clear_proxyid() {
  proxyid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::_internal_proxyid() const {
  return proxyid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::proxyid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.ProxyID)
  return _internal_proxyid();
}
inline void CreatePaymentReq::_internal_set_proxyid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  proxyid_ = value;
}
inline void CreatePaymentReq::set_proxyid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_proxyid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.ProxyID)
}

// int32 ClientID = 10;
inline void CreatePaymentReq::clear_clientid() {
  clientid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::_internal_clientid() const {
  return clientid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 CreatePaymentReq::clientid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentReq.ClientID)
  return _internal_clientid();
}
inline void CreatePaymentReq::_internal_set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  clientid_ = value;
}
inline void CreatePaymentReq::set_clientid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_clientid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentReq.ClientID)
}

// -------------------------------------------------------------------

// CreatePaymentAck

// uint32 RetCode = 1;
inline void CreatePaymentAck::clear_retcode() {
  retcode_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CreatePaymentAck::_internal_retcode() const {
  return retcode_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 CreatePaymentAck::retcode() const {
  // @@protoc_insertion_point(field_get:CreatePaymentAck.RetCode)
  return _internal_retcode();
}
inline void CreatePaymentAck::_internal_set_retcode(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  retcode_ = value;
}
inline void CreatePaymentAck::set_retcode(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_retcode(value);
  // @@protoc_insertion_point(field_set:CreatePaymentAck.RetCode)
}

// string OrderID = 2;
inline void CreatePaymentAck::clear_orderid() {
  orderid_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& CreatePaymentAck::orderid() const {
  // @@protoc_insertion_point(field_get:CreatePaymentAck.OrderID)
  return _internal_orderid();
}
inline void CreatePaymentAck::set_orderid(const std::string& value) {
  _internal_set_orderid(value);
  // @@protoc_insertion_point(field_set:CreatePaymentAck.OrderID)
}
inline std::string* CreatePaymentAck::mutable_orderid() {
  // @@protoc_insertion_point(field_mutable:CreatePaymentAck.OrderID)
  return _internal_mutable_orderid();
}
inline const std::string& CreatePaymentAck::_internal_orderid() const {
  return orderid_.Get();
}
inline void CreatePaymentAck::_internal_set_orderid(const std::string& value) {
  
  orderid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void CreatePaymentAck::set_orderid(std::string&& value) {
  
  orderid_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:CreatePaymentAck.OrderID)
}
inline void CreatePaymentAck::set_orderid(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  orderid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:CreatePaymentAck.OrderID)
}
inline void CreatePaymentAck::set_orderid(const char* value,
    size_t size) {
  
  orderid_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:CreatePaymentAck.OrderID)
}
inline std::string* CreatePaymentAck::_internal_mutable_orderid() {
  
  return orderid_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* CreatePaymentAck::release_orderid() {
  // @@protoc_insertion_point(field_release:CreatePaymentAck.OrderID)
  return orderid_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void CreatePaymentAck::set_allocated_orderid(std::string* orderid) {
  if (orderid != nullptr) {
    
  } else {
    
  }
  orderid_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), orderid,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:CreatePaymentAck.OrderID)
}
inline std::string* CreatePaymentAck::unsafe_arena_release_orderid() {
  // @@protoc_insertion_point(field_unsafe_arena_release:CreatePaymentAck.OrderID)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return orderid_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void CreatePaymentAck::unsafe_arena_set_allocated_orderid(
    std::string* orderid) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (orderid != nullptr) {
    
  } else {
    
  }
  orderid_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      orderid, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CreatePaymentAck.OrderID)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Msg_5fPayment_2eproto
